question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]
question_data2= {"response_code": 0, "results":
    [{"type": "boolean", "difficulty": "hard", "category": "Mythology",
      "question": "Janus was the Roman god of doorways and passageways.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                  "question": "A bear does NOT defecate during hibernation. ", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "Pluto is a planet.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
                                  "question": "The chemical element Lithium is named after the country of Lithuania.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                                  "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "History",
                                  "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                  "question": "You can legally drink alcohol while driving in Mississippi.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
                                  "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                                  "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
                                  "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                  "question": "The first IBM PC was released in 1981.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
                                  "question": "&quot;Neutral Milk Hotel&quot; is a real band.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                  "question": "SCP-173 was the first SCP article written for the web-based collaborative fiction project known as the &quot;SCP Foundation&quot;",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "hard",
                                  "category": "Entertainment: Japanese Anime &amp; Manga",
                                  "question": "The protagonist in &quot;Humanity Has Declined&quot; has no discernable name and is simply referred to as &#039;I&#039; for most of the series.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "History",
                                  "question": "The Spitfire originated from a racing plane.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                                  "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                  "question": "JavaScript derives from a later version of Java",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
                                  "question": "E = MC3", "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
                                  "question": "Super Mario and Paarthurnax (Skyrim) are voiced by the same actor.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                                  "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
                                  "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                                  "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                                  "question": "An average human can go two weeks without water.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]}]}
